### ISSUE TITLE
Dev. Test app

### ISSUE THREAD

**Issue by Snorri1986** [Snorri1986/MobileMessConvertor#9]
Write test methods for checking all methods which get calculated result(C++).
Correct values should get from Google conversion.

**Comment by Snorri1986** [comment]
java.lang.UnsatisfiedLinkError: no native-lib in java.library.path

	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.snorri.mobilemessconvertor.ExampleUnitTest.<clinit>

**Comment by Snorri1986** [comment]
C++ methods check manualy. Buttons - automatically.

**Comment by Snorri1986** [comment]
Manual tests have executed.

**Comment by Snorri1986** [comment]
Writting test cases for button are not needed.
